server {
        listen 80;
        server_name localhost;
        
        resolver 127.0.0.11 valid=10s;
        resolver_timeout 5s;

        location /grafana {
                rewrite ^/grafana/?(.*)$ /$1 break;
                proxy_pass http://grafana:3000;
           #return 301 http://$host:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
         }
        location /version {
                default_type text/plain;
                return 200 "Iteration 11";
        }
}
