---
version: "3.8"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

services: 
  prometheus:
    image: prom/prometheus:v3.15.0-rc.0
    container_name: prometheus
    ports:
      - "9090:9090"
    expose:
      - 9323
    volumes:
      - /etc/prometheus:/config
      - prometheus-data:/prometheus
    restart: unless-stopped
    command: 
      - "--config.file=/config/prometheus.yml"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging: *default-logging
  
  grafana:
    image: grafana/grafana:13.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    logging: *default-logging

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.12.1
    container_name: node-exporter
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    logging: *default-logging

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8081:8080"
    restart: unless-stopped
    logging: *default-logging

  loki:
    container_name: loki
    image: grafana/loki:main-1edb46b
    ports:
      - "3100:3100"
    volumes: 
      - ./config/loki/loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml
    restart: unless-stopped
    logging: *default-logging

  promtail:
    image: grafana/promtail:3.6.1
    container_name: promtail
    volumes:
      - ./config/promtail/promtail.yaml:/etc/promtail/promtail-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/:/var/log:ro,rslave
    command: -config.file=/etc/promtail/promtail-config.yaml
    restart: unless-stopped
    logging: *default-logging

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
